#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@

# Optional: install TPROXY dependencies (best-effort)
opkg install kmod-nft-tproxy kmod-nft-socket iptables-mod-tproxy iptables-mod-socket 2>/dev/null || true
